import './globals.css'
import NavBar from './components/NavBar'
import './globals.css'
import { Dancing_Script, Montserrat, } from 'next/font/google'

const montserrat = Montserrat({ subsets: ['latin'], variable: '--font-mont' })
const dancing_script = Dancing_Script({ subsets: ['latin'], weight: '700', variable: '--font-dancing' })


export const metadata = {
  title: 'Café da Vinci',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <body className={`${montserrat.variable} ${dancing_script.variable}  min-h-screen bg-light`}>

      <NavBar />
      {children}

    </body>
  )
}
